### ISSUE TITLE
Install & Enable w/o device bug

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/rtlsdr_pi#13]
When a current windows compile is installed and enabled, the menu opens and info, information and about all work fine. I can close the plugin also.

However when I shutdown opencpn and the reopen, when rtlsdr has been enabled, I am no longer able to access the Options menu, nothing happens.  

To fix this I had to edit the opencpn.ini and turn rtlsdr_pi=0

**Comment by seandepagnier** [comment]
I don't know about using the plugin on windows.
