### ISSUE TITLE
-r 48k vs -r 48000

### ISSUE THREAD

**Issue by tchiwam** [seandepagnier/rtlsdr_pi#14]
aplay -r 48k is not working on my system
aplay -r 48000 does work...

Could this be changed ?

**Comment by seandepagnier** [comment]
very strange.

In any case, you should probably use rtl_ais...   Are you listening to vhf radio or fm radio with the plugin?

**Comment by tchiwam** [comment]
Wed 15 Aug 2018 05:46:13 PM UTC: Execution failed
Stopped: rtl_fm -r 48k -s 250k -f 88.0M -l 0
Executing: Invalid FM frequency
Executed: aplay -r 12k -f S16_le -t raw -c 1
execvp(Invalid, FM, frequency) failed with error 2!

I also have an issue with the 88.0M it seems

**Comment by seandepagnier** [comment]
I see no issue with changing it

**Comment by tchiwam** [comment]
OK, seems the behaviour is similar on ubuntu and gentoo, from the manual writing 48 instead of 48k will work as all values under 300 are considered as kilohertz.

**Comment by pglez82** [comment]
I have changed this and made a pull request with my code. It is working now for me. #16
