### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by mschiff** [seandepagnier/rtlsdr_pi#4]
Hi!

It would be very usefull to have tagged releases, so the source for a specific version of th eplugin can be downloaded. Please add a release/tag for your released versions. This makes packaging a lot easier. 

I'd like to package this plugin for Gentoo Linux and for that it requires a reliable specific download URL for the releases. 

Thanks in advance!

**Comment by sailoog** [comment]
This was a fork just to add spanish translation, go to https://github.com/seandepagnier/rtlsdr_pi

**Comment by seandepagnier** [comment]
ok done
