### ISSUE TITLE
rtl_fm error on opening

### ISSUE THREAD

**Issue by sailoog** [seandepagnier/rtlsdr_pi#8]
Tested on fresh installation of PC-ubuntu and raspberry-raspian with the same error. Opencpn 4.0.0 and 4.1.0. All dependencies installed and running ok. Plugin compiled from repository.

Dongle connected, plugin activated and configured for rtl_fm aisdecoder. It is always returning an error "Error opening: rtl_fm -f 161975000 -p 63 -s 48k" at start because, I don't know why, 2 instances of rtl_fm are trying to be opened. If you deactivate and activate the plugin, everything will be stopped and started right and you can get AIS signal but if you close opencpn without doing that, an instance of rtl_fm will keep opened and it will be impossible start the plugin again.

**Comment by rgleason** [comment]
I noticed this several times in Windows, and thought it was a user error, but did not connect it to the possibility that it was the reason that it did not calibrate.
